services:
  dsm-website:
    build: .
    image: dsm-dev-website
    ports:
      - "${DSM_WEB_PORT}:3000"
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - dsm-web-dev-network
networks:
  dsm-web-dev-network:
    driver: bridge